package main

import (
	"bufio"
	"context"
	"fmt"
	"os"
	"strings"
)

func runSetup() {
	r := bufio.NewReader(os.Stdin)

	prompt := func(label, def string) string {
		if def != "" {
			fmt.Printf("  %s [%s]: ", label, def)
		} else {
			fmt.Printf("  %s: ", label)
		}
		line, _ := r.ReadString('\n')
		line = strings.TrimSpace(line)
		if line == "" {
			return def
		}
		return line
	}

	ok := func(msg string) { fmt.Printf("  ✓ %s\n", msg) }
	fail := func(msg string) { fmt.Printf("  ✗ %s\n", msg) }

	fmt.Println()
	fmt.Println("=== dune-admin setup ===")
	fmt.Println()

	fmt.Println("Checking for SSH key...")
	keyPath := resolveKeyPath()
	if _, err := os.Stat(keyPath); err != nil {
		fail("SSH key not found (checked ./sshKey, ~/.ssh/dune, ~/.ssh/id_ed25519, ~/.ssh/id_rsa)")
		fmt.Println()
		sshKeyPath = expandLocalPath(prompt("Path to SSH private key", ""))
		if sshKeyPath == "" {
			fmt.Fprintln(os.Stderr, "SSH key is required. Aborting.")
			os.Exit(1)
		}
		if _, err := os.Stat(sshKeyPath); err != nil {
			fmt.Fprintf(os.Stderr, "Key not found at %s. Aborting.\n", sshKeyPath)
			os.Exit(1)
		}
		keyPath = sshKeyPath
	} else {
		ok("SSH key: " + keyPath)
		sshKeyPath = keyPath
	}
	fmt.Println()

	fmt.Println("SSH connection:")
	sshHost = prompt("VM host:port", sshHost)
	sshUser = prompt("SSH user", sshUser)
	fmt.Println()

	fmt.Println("Database connection:")
	dbUser = prompt("DB user", dbUser)
	newDBPass := prompt("DB password", "")
	if newDBPass != "" {
		dbPass = newDBPass
	}
	if strings.TrimSpace(dbPass) == "" {
		fmt.Fprintln(os.Stderr, "DB password is required. Aborting.")
		os.Exit(1)
	}
	fmt.Println()

	fmt.Printf("Connecting via SSH to %s...\n", sshHost)
	client, err := dialSSH(keyPath)
	if err != nil {
		fail("SSH failed: " + err.Error())
		fmt.Println()
		fmt.Println("  Make sure:")
		fmt.Println("    - The VM is reachable at the given host:port")
		fmt.Println("    - The SSH key is authorized on the VM for that user")
		fmt.Println("    - The SSH user has passwordless sudo for kubectl, or Docker/Docker Compose is available")
		os.Exit(1)
	}
	ok("SSH connected")
	fmt.Println()

	if err := writeSetupEnv(false); err != nil {
		fail("Failed to write SSH config to .env: " + err.Error())
	} else {
		ok("SSH and DB config saved to .env")
	}
	fmt.Println()

	fmt.Println("Discovering database endpoint...")
	ns, pod, podIP, err := discoverDBPod(client)
	if err != nil {
		fail("Database endpoint discovery failed: " + err.Error())
		fmt.Println()
		fmt.Println("  SSH succeeded, but no supported Dune database service was found through Kubernetes, Docker Compose, or Docker.")
		fmt.Println("  Verify the game server stack is running on the target host and then re-run setup.")
		os.Exit(1)
	}
	globalSSH = client
	globalPodNS = ns
	globalPod = pod
	globalPodIP = podIP
	ok("Database endpoint: " + pod)
	fmt.Println()

	fmt.Println("Connecting to database...")
	pool, err := connectDB(context.Background(), dbUser, dbPass)
	if err != nil {
		fail("DB connect failed: " + err.Error())
		fmt.Println()
		fmt.Println("  SSH and endpoint discovery succeeded, but PostgreSQL rejected or closed the connection.")
		fmt.Println("  Verify the DB user, DB password, database name, and detected database port.")
		os.Exit(1)
	}
	globalDB = pool
	ok("Database connected as: " + dbUser)
	fmt.Println()

	fmt.Println("Server config:")
	listenAddr = prompt("HTTP listen address", listenAddr)
	fmt.Println()

	if err := writeSetupEnv(true); err != nil {
		fail("Failed to write .env: " + err.Error())
		os.Exit(1)
	}
	ok(".env written (chmod 600)")
	fmt.Println()

	fmt.Println("Setup complete.")
	fmt.Println()
	fmt.Println("  Build and run:  make build && ./dune-admin")
	fmt.Println("  Run (no build): go run .")
	fmt.Println()
}

func writeSetupEnv(includeDatabasePassword bool) error {
	quote := func(value string) string {
		if strings.ContainsAny(value, " \t#\"'") {
			return "\"" + strings.ReplaceAll(value, "\"", "\\\"") + "\""
		}
		return value
	}
	lines := []string{
		"# Generated by: dune-admin -setup",
		"",
		"SSH_HOST=" + quote(sshHost),
		"SSH_USER=" + quote(sshUser),
		"SSH_KEY=" + quote(keyPathForEnv()),
		"SSH_TUNNEL_MODE=" + quote(normalizedTunnelMode()),
		"SSH_TUNNEL_LOCAL_HOST=" + quote(sshTunnelHost),
		fmt.Sprintf("DB_TUNNEL_LOCAL_PORT=%d", dbTunnelLocalPort),
		"",
		fmt.Sprintf("DB_PORT=%d", dbPort),
		"DB_USER=" + quote(dbUser),
	}
	if includeDatabasePassword {
		lines = append(lines, "DB_PASS="+quote(dbPass))
	} else {
		lines = append(lines, "DB_PASS=")
	}
	lines = append(lines,
		"DB_NAME="+quote(dbName),
		"DB_SCHEMA="+quote(dbSchema),
		"",
		fmt.Sprintf("SCRIP_CURRENCY=%d", scripCurrencyID),
		"LISTEN_ADDR="+quote(listenAddr),
	)
	return os.WriteFile(".env", []byte(strings.Join(lines, "\n")+"\n"), 0600)
}

func keyPathForEnv() string {
	if sshKeyPath != "" {
		return expandLocalPath(sshKeyPath)
	}
	return resolveKeyPath()
}
