package main

import (
	"bufio"
	"context"
	"fmt"
	"os"
	"strings"
)

func runSetup() {
	r := bufio.NewReader(os.Stdin)

	ask := func(label, def string) string {
		if def != "" {
			fmt.Printf("  %s [%s]: ", label, def)
		} else {
			fmt.Printf("  %s: ", label)
		}
		line, _ := r.ReadString('\n')
		line = strings.TrimSpace(line)
		if line == "" {
			return def
		}
		return line
	}

	ok := func(msg string) { fmt.Printf("  ✓ %s\n", msg) }
	fail := func(msg string) { fmt.Printf("  ✗ %s\n", msg) }

	fmt.Println()
	fmt.Println("=== dune-admin setup ===")
	fmt.Println()

	fmt.Println("Checking for SSH key...")
	keyPath := resolveKeyPath()
	if _, err := os.Stat(keyPath); err != nil {
		fail("SSH key not found (checked ./sshKey, ~/.ssh/dune, ~/.ssh/id_ed25519, ~/.ssh/id_rsa)")
		fmt.Println()
		sshKeyPath = expandLocalPath(ask("Path to SSH private key", ""))
		if sshKeyPath == "" {
			fmt.Fprintln(os.Stderr, "SSH key is required. Aborting.")
			os.Exit(1)
		}
		if _, err := os.Stat(sshKeyPath); err != nil {
			fmt.Fprintf(os.Stderr, "Key not found at %s. Aborting.\n", sshKeyPath)
			os.Exit(1)
		}
		keyPath = sshKeyPath
	} else {
		ok("SSH key: " + keyPath)
		sshKeyPath = keyPath
	}
	fmt.Println()

	fmt.Println("SSH connection:")
	sshHost = ask("VM host:port", sshHost)
	sshUser = ask("SSH user", sshUser)
	fmt.Println()

	fmt.Printf("Connecting via SSH to %s...\n", sshHost)
	client, err := dialSSH(keyPath)
	if err != nil {
		fail("SSH failed: " + err.Error())
		fmt.Println()
		fmt.Println("  Make sure:")
		fmt.Println("    - The VM is reachable at the given host:port")
		fmt.Println("    - The SSH key is authorized on the VM for that user")
		fmt.Println("    - The SSH user has passwordless sudo for kubectl")
		os.Exit(1)
	}
	ok("SSH connected")
	fmt.Println()

	if err := writeSetupEnv(false); err != nil {
		fail("Failed to write SSH config to .env: " + err.Error())
	} else {
		ok("SSH config saved to .env")
	}
	fmt.Println()

	fmt.Println("Discovering database pod...")
	ns, pod, podIP, err := discoverDBPod(client)
	if err != nil {
		fail("Pod discovery failed: " + err.Error())
		fmt.Println()
		fmt.Println("  SSH settings were saved. Run the commands below on the VM to inspect pod names:")
		fmt.Println("    sudo kubectl get pods -A -o wide")
		fmt.Println("    sudo kubectl get svc -A -o wide")
		os.Exit(1)
	}
	globalSSH = client
	globalPodNS = ns
	globalPod = pod
	globalPodIP = podIP
	ok("Database pod: " + pod)
	fmt.Println()

	fmt.Println("Discovering database password...")
	discoveredUser := "postgres"
	discoveredPass := ""
	var battlegroups []string
	if bg := battlegroupFromPod(globalPod); bg != "" {
		battlegroups = []string{bg}
	} else {
		battlegroups = listBattlegroups(client)
	}
	if len(battlegroups) == 0 {
		fmt.Println("  Could not determine battlegroup name")
	} else {
		chosen := battlegroups[0]
		if len(battlegroups) > 1 {
			fmt.Println("  Available battlegroups:")
			for i, bg := range battlegroups {
				fmt.Printf("    [%d] %s\n", i+1, bg)
			}
			fmt.Println()
			idxStr := ask(fmt.Sprintf("Which battlegroup? [1-%d]", len(battlegroups)), "1")
			idx := 1
			fmt.Sscanf(idxStr, "%d", &idx)
			if idx >= 1 && idx <= len(battlegroups) {
				chosen = battlegroups[idx-1]
			}
		}
		yamlPath := fmt.Sprintf("~/.dune/%s.yaml", chosen)
		if u, pass := extractPasswordFromYAML(client, yamlPath); pass != "" {
			discoveredUser = u
			discoveredPass = pass
			ok(fmt.Sprintf("Password found in %s (user: %s)", yamlPath, u))
		} else {
			fail("No password found in " + yamlPath)
		}
	}
	if discoveredPass == "" {
		fmt.Println()
		fmt.Println("  Could not auto-discover the database password.")
		discoveredUser = ask("Database user", "postgres")
		discoveredPass = ask("Database password", "")
		if discoveredPass == "" {
			fmt.Fprintln(os.Stderr, "Database password is required. Aborting.")
			os.Exit(1)
		}
	}
	fmt.Println()

	fmt.Println("Connecting to database...")
	dbUser = discoveredUser
	dbPass = discoveredPass
	pool, err := connectDB(context.Background(), discoveredUser, discoveredPass)
	if err != nil {
		fail("DB connect failed: " + err.Error())
		fmt.Println()
		fmt.Println("  The password may be wrong. Re-run setup to try again.")
		os.Exit(1)
	}
	globalDB = pool
	ok("Database connected as: " + dbUser)
	fmt.Println()

	fmt.Println("Server config:")
	listenAddr = ask("HTTP listen address", listenAddr)
	fmt.Println()

	if err := writeSetupEnv(true); err != nil {
		fail("Failed to write .env: " + err.Error())
		os.Exit(1)
	}
	ok(".env written (chmod 600)")
	fmt.Println()

	fmt.Println("Setup complete.")
	fmt.Println()
	fmt.Println("  Build and run:  make build && ./dune-admin")
	fmt.Println("  Run (no build): go run .")
	fmt.Println()
}

func writeSetupEnv(includeDatabasePassword bool) error {
	quote := func(value string) string {
		if strings.ContainsAny(value, " \t#\"'") {
			return "\"" + strings.ReplaceAll(value, "\"", "\\\"") + "\""
		}
		return value
	}
	lines := []string{
		"# Generated by: dune-admin -setup",
		"",
		"SSH_HOST=" + quote(sshHost),
		"SSH_USER=" + quote(sshUser),
		"SSH_KEY=" + quote(keyPathForEnv()),
		"SSH_TUNNEL_MODE=" + quote(normalizedTunnelMode()),
		"SSH_TUNNEL_LOCAL_HOST=" + quote(sshTunnelHost),
		fmt.Sprintf("DB_TUNNEL_LOCAL_PORT=%d", dbTunnelLocalPort),
		"",
		fmt.Sprintf("DB_PORT=%d", dbPort),
		"DB_USER=" + quote(dbUser),
	}
	if includeDatabasePassword {
		lines = append(lines, "DB_PASS="+quote(dbPass))
	} else {
		lines = append(lines, "DB_PASS=")
	}
	lines = append(lines,
		"DB_NAME="+quote(dbName),
		"DB_SCHEMA="+quote(dbSchema),
		"",
		fmt.Sprintf("SCRIP_CURRENCY=%d", scripCurrencyID),
		"LISTEN_ADDR="+quote(listenAddr),
	)
	return os.WriteFile(".env", []byte(strings.Join(lines, "\n")+"\n"), 0600)
}

func keyPathForEnv() string {
	if sshKeyPath != "" {
		return expandLocalPath(sshKeyPath)
	}
	return resolveKeyPath()
}
