#!/usr/bin/env bash

REPO_ROOT="${REPO_ROOT:-}"
OUTPUT_DIR="${OUTPUT_DIR:-}"
VERSION="${VERSION:-dev}"
COMMIT_MESSAGE="${COMMIT_MESSAGE:-Automated successful update}"
CLEAN_WEB_DEPENDENCIES="${CLEAN_WEB_DEPENDENCIES:-0}"
SKIP_WEB_INSTALL="${SKIP_WEB_INSTALL:-0}"
SKIP_GIT_PULL="${SKIP_GIT_PULL:-0}"
SKIP_GO_TESTS="${SKIP_GO_TESTS:-0}"
SKIP_WEB_AUDIT="${SKIP_WEB_AUDIT:-0}"
SKIP_WEB_TYPECHECK="${SKIP_WEB_TYPECHECK:-0}"
SKIP_WEB_LINT="${SKIP_WEB_LINT:-0}"
SKIP_WEB_BUILD="${SKIP_WEB_BUILD:-0}"
SKIP_NPM_REPAIR="${SKIP_NPM_REPAIR:-0}"
SKIP_AUTO_COMMIT="${SKIP_AUTO_COMMIT:-0}"
SKIP_AUTO_PUSH="${SKIP_AUTO_PUSH:-0}"
ALLOW_DIRTY_WORKTREE="${ALLOW_DIRTY_WORKTREE:-0}"
SKIP_ROOT_BINARY_COPY="${SKIP_ROOT_BINARY_COPY:-0}"
SKIP_PREREQ_INSTALL="${SKIP_PREREQ_INSTALL:-0}"

INITIAL_DIR="$(pwd)"
UPDATE_SUCCEEDED=0
AUTO_COMMIT_SHA=""
WEB_ROOT=""
BUILD_OUTPUT_DIR=""
BACKEND_BINARY=""
REPO_ROOT_BINARY=""
BINARY_NAME="arrakis-control-panel"
GOOS_VALUE=""

COLOR_RESET=$'\033[0m'
COLOR_DIM=$'\033[90m'
COLOR_CYAN=$'\033[36m'
COLOR_GREEN=$'\033[32m'
COLOR_RED=$'\033[31m'
COLOR_YELLOW=$'\033[33m'

resolve_update_paths() {
  if [[ -z "$REPO_ROOT" ]]; then
    REPO_ROOT="$SCRIPT_DIR"
  fi
  REPO_ROOT="$(cd "$REPO_ROOT" && pwd -P)"
  WEB_ROOT="$REPO_ROOT/web"
}
